drupal/web/modules/custom/gentle_panther/src/Form/ReportRevisionRevertForm.php
<?php

namespace Drupal\gentle_panther\Form;

use Drupal\Core\Datetime\DateFormatterInterface;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\gentle_panther\Entity\ReportInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a form for reverting a Report revision.
 *
 * @ingroup gentle_panther
 */
class ReportRevisionRevertForm extends ConfirmFormBase {


  /**
   * The Report revision.
   *
   * @var \Drupal\gentle_panther\Entity\ReportInterface
   */
  protected $revision;

  /**
   * The Report storage.
   *
   * @var \Drupal\Core\Entity\EntityStorageInterface
   */
  protected $ReportStorage;

  /**
   * The date formatter service.
   *
   * @var \Drupal\Core\Datetime\DateFormatterInterface
   */
  protected $dateFormatter;

  /**
   * Constructs a new ReportRevisionRevertForm.
   *
   * @param \Drupal\Core\Entity\EntityStorageInterface $entity_storage
   *   The Report storage.
   * @param \Drupal\Core\Datetime\DateFormatterInterface $date_formatter
   *   The date formatter service.
   */
  public function __construct(EntityStorageInterface $entity_storage, DateFormatterInterface $date_formatter) {
    $this->ReportStorage = $entity_storage;
    $this->dateFormatter = $date_formatter;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('entity.manager')->getStorage('report'),
      $container->get('date.formatter')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'report_revision_revert_confirm';
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return t('Are you sure you want to revert to the revision from %revision-date?', ['%revision-date' => $this->dateFormatter->format($this->revision->getRevisionCreationTime())]);
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    return new Url('entity.report.version_history', ['report' => $this->revision->id()]);
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return t('Revert');
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return '';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, $report_revision = NULL) {
    $this->revision = $this->ReportStorage->loadRevision($report_revision);
    $form = parent::buildForm($form, $form_state);

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    // The revision timestamp will be updated when the revision is saved. Keep
    // the original one for the confirmation message.
    $original_revision_timestamp = $this->revision->getRevisionCreationTime();

    $this->revision = $this->prepareRevertedRevision($this->revision, $form_state);
    $this->revision->revision_log = t('Copy of the revision from %date.', ['%date' => $this->dateFormatter->format($original_revision_timestamp)]);
    $this->revision->save();

    $this->logger('content')->notice('Report: reverted %title revision %revision.', ['%title' => $this->revision->label(), '%revision' => $this->revision->getRevisionId()]);
    drupal_set_message(t('Report %title has been reverted to the revision from %revision-date.', ['%title' => $this->revision->label(), '%revision-date' => $this->dateFormatter->format($original_revision_timestamp)]));
    $form_state->setRedirect(
      'entity.report.version_history',
      ['report' => $this->revision->id()]
    );
  }

  /**
   * Prepares a revision to be reverted.
   *
   * @param \Drupal\gentle_panther\Entity\ReportInterface $revision
   *   The revision to be reverted.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The current state of the form.
   *
   * @return \Drupal\gentle_panther\Entity\ReportInterface
   *   The prepared revision ready to be stored.
   */
  protected function prepareRevertedRevision(ReportInterface $revision, FormStateInterface $form_state) {
    $revision->setNewRevision();
    $revision->isDefaultRevision(TRUE);
    $revision->setRevisionCreationTime(REQUEST_TIME);

    return $revision;
  }

}

drupal/web/modules/custom/gentle_panther/templates/choose-report.html.twig
{% for type in report_types %}
  <article>
    <h2>{{ type.name }}</h2>
    <p>{{ type.description }}</p>
    <p>
      <a href="{{ path(type.route) }}">Make a {{ type.name }} Report</a>
    </p>
  </article>
{% endfor %}

drupal/web/modules/custom/gentle_panther/templates/gentle-panther.html.twig
<!-- Add you custom twig html here -->

drupal/web/modules/custom/gentle_panther/templates/report-content-add-list.html.twig
{#
/**
 * @file
 * Default theme implementation to present a list of custom content entity types/bundles.
 *
 * Available variables:
 * - types: A collection of all the available custom entity types/bundles.
 *   Each type/bundle contains the following:
 *   - link: A link to add a content entity of this type.
 *   - description: A description of this content entity types/bundle.
 *
 * @see template_preprocess_report_content_add_list()
 *
 * @ingroup themeable
 */
#}
{% spaceless %}
  <dl>
    {% for type in types %}
      <dt>{{ type.link }}</dt>
    {% endfor %}
  </dl>
{% endspaceless %}

drupal/web/modules/custom/gentle_panther/templates/report.html.twig
{#
/**
 * @file report.html.twig
 * Default theme implementation to present Report data.
 *
 * This template is used when viewing Report pages.
 *
 *
 * Available variables:
 * - content: A list of content items. Use 'content' to print all content, or
 * - attributes: HTML attributes for the container element.
 *
 * @see template_preprocess_report()
 *
 * @ingroup themeable
 */
#}
<div{{ attributes.addClass('report') }}>
  {% if content %}
    {{- content -}}
  {% endif %}
</div>